---
- hosts: database
  become: true
  tasks:
    - name: install tools
      dnf:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - python3-PyMySQL

    - name: install mysql-server VERSION CENTOS
      dnf: 
          name:  mysql-server
          state: present 
          update_cache: yes

    - name: chequear que haya iniciado my sql con systemd (systemctl es el comando de base enc centos)
      systemd:
          name: mysqld
          state: started
          enabled: yes


    - name: ensure mysql listening on all ports
      lineinfile: 
          dest: /etc/my.cnf.d/mysql-server.cnf 
          regexp: '^bind-address' 
          line: 'bind-address = 0.0.0.0'
      notify: 
          - restart mysql

    - name: create demo database
      mysql_db: 
        name: 
          - demo 
        state: present

    - name: create demo user
      mysql_user: 
        name: demo 
        password: demo 
        priv: 'demo.*:ALL' 
        host: '%' 
        state: present

  handlers:
    - name: restart mysql
      dnf: 
        name: mysql 
        state: restarted