---
- hosts: loadbalancer
  become: true
  tasks:
    - name: parando loadbalancer
      systemd:
         name: "{{ item }}"
         state: stopped
         enabled: yes
      loop:
          - nginx
    - wait_for: 
        port: 80 
        state: drained

- hosts: webserver
  become: true
  tasks:
    - name: parando webserver
      systemd:
         name: "{{ item }}"
         state: stopped
         enabled: yes
      loop:
          - httpd
    - wait_for: 
        port: 80 
        state: stopped
    
- hosts: database
  become: true
  tasks:
    - name: reiniciando mysql
      systemd:
         name: "{{ item }}"
         state: restarted
         enabled: yes
      loop:
          - mysqld
    - wait_for: 
        port: 3306 
        state: started

- hosts: webserver
  become: true
  tasks:
    - name: iniciando webserver
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
      loop:
          - httpd
    - wait_for: 
        port: 80

- hosts: loadbalancer
  become: true
  tasks:
    - name: iniciando loadbalancer
      systemd:
         name: "{{ item }}"
         state: started
         enabled: yes
      loop:
          - nginx
    - wait_for: 
        port: 80
