---
- hosts: webserver
  become: true

  roles:
    - apache2
    # - {role: demo_app, db_user: demo, db_pass: demo, db_name: demo } para el cambio 37 esto queda redundante dado el agrupaminento de variables, así que se cambia.
    #
    #
    #cambio a estos nombres de variables, tanto aquí como en el template, porque en databaseCENTOS.yml tenemos otras variables.
    #{ role: demo_app, db_user: demo, db_user: demo, db_name: demo }
    #'mysql://{{ db_user }}:{{ db_pass }}@{{ groups.database[0] }}/{{ db_name }}'
    - demo_app