---
- name: install tools
  dnf:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - python3-PyMySQL

- name: install mysql-server VERSION CENTOS
  dnf: 
      name:  mysql-server
      state: present 
      update_cache: yes

- name: ensure mysql listening on all ports
  lineinfile: 
      dest: /etc/my.cnf.d/mysql-server.cnf 
      regexp: '^bind-address' 
      line: 'bind-address = {{ansible_eth0.ipv4.address}}'
  notify: 
      - restart mysql

- name: chequear que haya iniciado my sql con systemd (systemctl es el comando de base enc centos)
  systemd:
      name: mysqld
      state: started
      enabled: yes

- name: create demo database
  mysql_db: 
    name: 
      - demo 
    state: present

- name: create demo user
  mysql_user: 
    name: demo 
    password: demo 
    priv: 'demo.*:ALL' 
    host: '%' 
    state: present
